use assert_cmd::Command;
use astra_actions::{resolve_actions, ProjectReference};
use astra_execution::ExecutionEngine;
use astra_knowledge::{
    Confidence as KnowledgeConfidence, Evidence, EvidenceKind, KnowledgeCategory, KnowledgeClaim,
    KnowledgeNamespace, KnowledgeStore, Validity, ValidityCondition,
};
use predicates::prelude::*;
use serde_json::Value;
use std::{fs, path::Path, process::Command as ProcessCommand};
use tempfile::{tempdir, TempDir};

fn project() -> TempDir {
    let directory = tempdir().expect("project directory");
    write_project_at(directory.path());
    directory
}

fn write_project_at(directory: &Path) {
    fs::create_dir_all(directory.join("src")).expect("source directory");
    fs::write(
        directory.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\n",
    )
    .expect("workspace manifest");
    fs::write(directory.join("src/lib.rs"), "pub fn ready() {}\n").expect("source");
}

fn project_without_commands() -> TempDir {
    let directory = tempdir().expect("project directory");
    fs::write(directory.path().join("README.md"), "# No actions\n").expect("readme");
    directory
}

fn git_project() -> TempDir {
    let directory = project();
    fs::write(
        directory.path().join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\nresolver = \"2\"\n",
    )
    .expect("package manifest");
    fs::write(
        directory.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("lockfile");
    fs::write(directory.path().join(".gitignore"), "target/\n").expect("gitignore");
    git(directory.path(), &["init", "-q"]);
    git(directory.path(), &["config", "user.name", "Astra Test"]);
    git(
        directory.path(),
        &["config", "user.email", "astra@example.invalid"],
    );
    git(directory.path(), &["add", "."]);
    git(directory.path(), &["commit", "-qm", "initial"]);
    directory
}

fn git(root: &Path, arguments: &[&str]) {
    let status = ProcessCommand::new("git")
        .args(arguments)
        .current_dir(root)
        .env("GIT_CONFIG_NOSYSTEM", "1")
        .env(
            "GIT_CONFIG_GLOBAL",
            if cfg!(windows) { "NUL" } else { "/dev/null" },
        )
        .status()
        .expect("Git command");
    assert!(status.success(), "Git command failed: {arguments:?}");
}

fn write_config(home: &Path, entries: &[(&str, &Path)]) {
    let config_dir = home.join("astra-config");
    fs::create_dir_all(&config_dir).expect("config directory");
    let mut config = String::from(
        "[workspace]\nroot = \"/tmp/workspaces\"\n\n[editor]\ncommand = \"true\"\n\n[ai]\nprovider = \"ollama\"\n\n[cyber]\nlabs = \"/tmp/cyber\"\n\n[workspaces]\n",
    );
    for (name, path) in entries {
        config.push_str(&format!("{name} = {:?}\n", path.to_string_lossy()));
    }
    fs::write(config_dir.join("config.toml"), config).expect("configuration");
}

fn astra(home: &Path, current_dir: &Path) -> Command {
    let mut command = Command::cargo_bin("astra").expect("binary");
    command
        .env("HOME", home)
        .env("ASTRA_CONFIG_DIR", home.join("astra-config"))
        .env("PATH", "")
        .current_dir(current_dir);
    command
}

fn astra_with_path(home: &Path, current_dir: &Path) -> Command {
    let mut command = Command::cargo_bin("astra").expect("binary");
    command
        .env("HOME", home)
        .env("ASTRA_CONFIG_DIR", home.join("astra-config"))
        .current_dir(current_dir);
    command
}

#[test]
fn project_help_lists_the_explicit_subcommands() {
    astra(tempdir().expect("home").path(), Path::new("."))
        .args(["project", "--help"])
        .assert()
        .success()
        .stdout(predicate::str::contains("list"))
        .stdout(predicate::str::contains("inspect"))
        .stdout(predicate::str::contains("commands"))
        .stdout(predicate::str::contains("run"))
        .stdout(predicate::str::contains("understand"))
        .stdout(predicate::str::contains("create"));
}

#[test]
fn project_understand_is_deterministic_read_only_and_hides_knowledge_values() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);
    let knowledge_root = home.path().join(".astra/knowledge");
    let store = KnowledgeStore::open(&knowledge_root);
    let claim = KnowledgeClaim::new(
        KnowledgeCategory::Fact,
        "project:demo",
        "has_private_note",
        serde_json::json!("ASTRA_INTELLIGENCE_SECRET_SENTINEL"),
        vec![Evidence::new(
            EvidenceKind::ContextFact,
            "fact:private-note",
        )],
        KnowledgeConfidence::High,
        Validity::Current,
    )
    .and_then(|claim| claim.with_created_at("2026-01-01T00:00:00Z"))
    .expect("claim");
    store
        .add_claim(&KnowledgeNamespace::project("demo"), &claim)
        .expect("stored claim");
    let before_project = fs::read(project.path().join("Cargo.toml")).expect("manifest");
    let before_claim = fs::read(
        knowledge_root
            .join("projects/demo/facts")
            .join(format!("{}.json", claim.id)),
    )
    .expect("claim file");

    let first = astra(home.path(), current.path())
        .args(["project", "understand", "demo", "--json"])
        .output()
        .expect("understanding output");
    let second = astra(home.path(), current.path())
        .args(["project", "understand", "demo", "--json"])
        .output()
        .expect("repeat understanding output");
    assert!(first.status.success());
    assert_eq!(first.stdout, second.stdout);
    let json: Value = serde_json::from_slice(&first.stdout).expect("understanding JSON");
    assert_eq!(json["schema_version"], 1);
    assert_eq!(json["project"]["name"], "demo");
    let output = String::from_utf8(first.stdout).expect("UTF-8 output");
    assert!(!output.contains("ASTRA_INTELLIGENCE_SECRET_SENTINEL"));
    assert!(!output.contains(project.path().to_string_lossy().as_ref()));
    assert_eq!(
        fs::read(project.path().join("Cargo.toml")).expect("manifest"),
        before_project
    );
    assert_eq!(
        fs::read(
            knowledge_root
                .join("projects/demo/facts")
                .join(format!("{}.json", claim.id))
        )
        .expect("claim file"),
        before_claim
    );
}

#[test]
fn project_understand_projects_a_stale_verification_without_running_cargo() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = git_project();
    write_config(home.path(), &[("demo", project.path())]);
    let report =
        astra_context::ProjectAnalyzer::without_processes(astra_context::ScanOptions::default())
            .expect("analyzer")
            .analyze(project.path())
            .expect("context report");
    let actions = resolve_actions(&report.context.validation_commands);
    let check = actions
        .into_iter()
        .find(|action| action.id == astra_actions::ActionId::Check)
        .expect("check action");
    let state = ExecutionEngine::new()
        .plan(
            &ProjectReference {
                name: "demo".to_string(),
                root: project.path().canonicalize().expect("canonical root"),
            },
            &check,
        )
        .expect("state plan")
        .source_state
        .combined_fingerprint
        .to_string();
    let knowledge_root = home.path().join(".astra/knowledge");
    let claim = KnowledgeClaim::new(
        KnowledgeCategory::Verification,
        "project:demo",
        "check",
        serde_json::json!({"action":"check", "verdict":"verified_check"}),
        vec![Evidence::new(
            EvidenceKind::ExecutionResult,
            "execution:stale",
        )],
        KnowledgeConfidence::Certain,
        Validity::Current,
    )
    .and_then(|claim| claim.with_created_at("2026-01-01T00:00:00Z"))
    .map(|claim| {
        claim.with_validity_conditions(vec![ValidityCondition::state_bound(
            format!("different-{state}"),
            "action-fingerprint",
            "plan-fingerprint",
        )])
    })
    .expect("verification claim");
    KnowledgeStore::open(&knowledge_root)
        .add_claim(&KnowledgeNamespace::project("demo"), &claim)
        .expect("stored claim");

    astra_with_path(home.path(), current.path())
        .args(["project", "understand", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "The latest verification does not apply to the current project state.",
        ))
        .stdout(predicate::str::contains(
            "The latest verification is stale for the current project state.",
        ))
        .stdout(predicate::str::contains("Executing approved plan").not());
}

#[test]
fn project_run_help_requires_and_describes_dry_run() {
    astra(
        tempdir().expect("home").path(),
        tempdir().expect("current directory").path(),
    )
    .args(["project", "run", "--help"])
    .assert()
    .success()
    .stdout(predicate::str::contains("<NAME>"))
    .stdout(predicate::str::contains("<ACTION>"))
    .stdout(predicate::str::contains("--dry-run"))
    .stdout(predicate::str::contains("without starting a process"));
}

#[test]
fn legacy_ambiguous_project_positionals_are_rejected_in_favor_of_create() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");

    astra(home.path(), current.path())
        .args(["project", "node", "demo"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("unrecognized subcommand"));
}

#[test]
fn project_list_is_deterministic_and_aligned() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    write_config(
        home.path(),
        &[
            ("beta", Path::new("/tmp/beta")),
            ("alpha", Path::new("/tmp/alpha")),
        ],
    );

    let first = astra(home.path(), current.path())
        .args(["project", "list"])
        .output()
        .expect("first list output");
    let second = astra(home.path(), current.path())
        .args(["project", "list"])
        .output()
        .expect("second list output");

    assert!(first.status.success());
    assert!(second.status.success());
    assert_eq!(first.stdout, second.stdout);
    assert_eq!(
        String::from_utf8(first.stdout).expect("list output is UTF-8"),
        "PROJECT  PATH\nalpha    /tmp/alpha\nbeta     /tmp/beta\n"
    );
}

#[test]
fn project_list_without_config_does_not_create_a_config_file() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let config_path = home.path().join("astra-config/config.toml");

    astra(home.path(), current.path())
        .args(["project", "list"])
        .assert()
        .success()
        .stdout(predicate::str::contains("PROJECT"));

    assert!(!config_path.exists());
}

#[test]
fn project_inspect_resolves_a_registered_project_and_supports_json() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);

    astra(home.path(), current.path())
        .args(["project", "inspect", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Project: "))
        .stdout(predicate::str::contains("Packages:"));

    astra(home.path(), current.path())
        .args(["project", "inspect", "demo", "--json"])
        .assert()
        .success()
        .stdout(predicate::str::contains("\"schema_version\": 1"))
        .stdout(predicate::str::contains("\"demo\"").not());
}

#[test]
fn project_commands_discovers_build_check_and_test_without_execution() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);

    astra(home.path(), current.path())
        .args(["project", "commands", "demo"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Available actions for demo"))
        .stdout(predicate::str::contains("build   cargo build --workspace"))
        .stdout(predicate::str::contains("check   cargo check --workspace"))
        .stdout(predicate::str::contains("test    cargo test --workspace"));
}

#[test]
fn project_commands_json_is_versioned_and_structured() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);

    let output = astra(home.path(), current.path())
        .args(["project", "commands", "demo", "--json"])
        .output()
        .expect("command output");
    assert!(output.status.success());
    let json: Value = serde_json::from_slice(&output.stdout).expect("action JSON");
    assert_eq!(json["schema_version"], 1);
    assert_eq!(json["project"]["name"], "demo");
    assert_eq!(
        json["project"]["root"],
        project
            .path()
            .canonicalize()
            .expect("canonical project")
            .to_string_lossy()
            .as_ref()
    );
    let actions = json["actions"].as_array().expect("actions array");
    assert_eq!(actions.len(), 3);
    assert_eq!(actions[0]["id"], "build");
    assert_eq!(actions[1]["id"], "check");
    assert_eq!(actions[2]["id"], "test");
    assert_eq!(actions[0]["executable"], "cargo");
    assert_eq!(
        actions[0]["arguments"],
        serde_json::json!(["build", "--workspace"])
    );
    assert_eq!(actions[0]["working_directory"], json["project"]["root"]);
    assert_eq!(actions[0]["source"], "context_engine");
    assert_eq!(actions[0]["confidence"], "high");
}

#[test]
fn unknown_and_missing_projects_fail_concisely() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    write_config(
        home.path(),
        &[("missing", &current.path().join("does-not-exist"))],
    );

    astra(home.path(), current.path())
        .args(["project", "commands", "nonexistent"])
        .assert()
        .failure()
        .stderr("astra: unknown project: nonexistent\n");
    astra(home.path(), current.path())
        .args(["project", "commands", "missing"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("project path does not exist"))
        .stderr(predicate::str::contains("ERROR").not());
}

#[test]
fn project_without_supported_actions_succeeds_with_a_clear_message() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project_without_commands();
    write_config(home.path(), &[("empty", project.path())]);

    astra(home.path(), current.path())
        .args(["project", "commands", "empty"])
        .assert()
        .success()
        .stdout(predicate::str::contains("No supported actions detected."));
}

#[test]
fn project_commands_never_executes_detected_commands() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);

    // PATH is empty, so an accidental cargo invocation would fail the command.
    astra(home.path(), current.path())
        .args(["project", "commands", "demo"])
        .assert()
        .success();
}

#[test]
fn project_run_dry_run_supports_build_check_and_test_without_execution() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);

    for action in ["build", "check", "test"] {
        let output = astra(home.path(), current.path())
            .args(["project", "run", "demo", action, "--dry-run"])
            .output()
            .expect("dry-run output");
        assert!(output.status.success(), "action {action} failed");
        let stdout = String::from_utf8(output.stdout).expect("UTF-8 output");
        assert!(stdout.contains(&format!("Action: {action}")));
        assert!(stdout.contains("Policy: allowed"));
        assert!(stdout.contains("Dry run complete. No process was started."));
    }
}

#[test]
fn project_run_json_is_versioned_and_never_starts_a_process() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);

    let output = astra(home.path(), current.path())
        .args(["project", "run", "demo", "check", "--dry-run", "--json"])
        .output()
        .expect("dry-run JSON");
    assert!(output.status.success());
    let json: Value = serde_json::from_slice(&output.stdout).expect("dry-run JSON");
    assert_eq!(json["schema_version"], 1);
    assert_eq!(json["project"]["name"], "demo");
    assert_eq!(json["action"]["id"], "check");
    assert_eq!(
        json["action"]["arguments"],
        serde_json::json!(["check", "--workspace"])
    );
    assert_eq!(json["policy"]["decision"], "allowed");
    assert_eq!(json["execution"]["mode"], "dry_run");
    assert_eq!(json["execution"]["process_started"], false);
}

#[test]
fn project_run_build_and_test_require_dry_run() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");

    astra(home.path(), current.path())
        .args(["project", "run", "demo", "build"])
        .assert()
        .failure()
        .stderr("astra: action is currently dry-run only: build\n");
    astra(home.path(), current.path())
        .args(["project", "run", "demo", "test"])
        .assert()
        .failure()
        .stderr("astra: action is currently dry-run only: test\n");
}

#[test]
fn project_run_reports_unknown_unsupported_and_unavailable_actions() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    let empty = project_without_commands();
    let missing = current.path().join("missing");
    write_config(
        home.path(),
        &[
            ("demo", project.path()),
            ("empty", empty.path()),
            ("missing", &missing),
        ],
    );

    astra(home.path(), current.path())
        .args(["project", "run", "nonexistent", "check", "--dry-run"])
        .assert()
        .failure()
        .stderr("astra: unknown project: nonexistent\n");
    astra(home.path(), current.path())
        .args(["project", "run", "demo", "deploy", "--dry-run"])
        .assert()
        .failure()
        .stderr("astra: unsupported action: deploy\n");
    astra(home.path(), current.path())
        .args(["project", "run", "empty", "check", "--dry-run"])
        .assert()
        .failure()
        .stderr("astra: project does not expose action: check for empty\n");
    astra(home.path(), current.path())
        .args(["project", "run", "missing", "check", "--dry-run"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("project path does not exist"));
}

#[test]
fn project_run_does_not_create_config_or_modify_project_files() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project_root = home.path().join("Developer/projects/astraos");
    write_project_at(&project_root);
    let manifest_before = fs::read(project_root.join("Cargo.toml")).expect("manifest");
    let source_before = fs::read(project_root.join("src/lib.rs")).expect("source");
    let config_path = home.path().join("astra-config/config.toml");

    astra(home.path(), current.path())
        .args(["project", "run", "astraos", "check", "--dry-run"])
        .assert()
        .success();

    assert!(!config_path.exists());
    assert_eq!(
        fs::read(project_root.join("Cargo.toml")).expect("manifest"),
        manifest_before
    );
    assert_eq!(
        fs::read(project_root.join("src/lib.rs")).expect("source"),
        source_before
    );
}

#[test]
fn project_run_real_check_requires_git_and_executes_dirty_states() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = git_project();
    write_config(home.path(), &[("demo", project.path())]);
    fs::write(project.path().join("src/staged.rs"), "pub fn staged() {}\n").expect("staged source");
    git(project.path(), &["add", "src/staged.rs"]);
    fs::write(
        project.path().join("src/lib.rs"),
        "pub fn ready() { let _ = 1; }\n",
    )
    .expect("unstaged source");
    fs::write(
        project.path().join("src/untracked.rs"),
        "pub fn untracked() {}\n",
    )
    .expect("untracked source");

    astra_with_path(home.path(), current.path())
        .args(["project", "run", "demo", "check"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Executing approved plan..."))
        .stdout(predicate::str::contains("Verdict: verified_check"))
        .stdout(predicate::str::contains("Source state changed: no"));
}

#[test]
fn project_run_real_check_json_keeps_stdout_as_valid_json() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = git_project();
    write_config(home.path(), &[("demo", project.path())]);

    let output = astra_with_path(home.path(), current.path())
        .args(["project", "run", "demo", "check", "--json"])
        .output()
        .expect("execution output");
    assert!(output.status.success());
    let json: Value = serde_json::from_slice(&output.stdout).expect("execution JSON");
    assert_eq!(json["schema_version"], 1);
    assert_eq!(json["execution"]["process_started"], true);
    assert_eq!(json["execution"]["verdict"], "verified_check");
    assert_eq!(json["state"]["changed"], false);
    assert!(String::from_utf8_lossy(&output.stdout).contains("plan_fingerprint"));
}

#[test]
fn project_run_real_check_persists_fingerprint_only_verification_knowledge() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let knowledge = tempdir().expect("knowledge");
    let project = git_project();
    write_config(home.path(), &[("demo", project.path())]);

    astra_with_path(home.path(), current.path())
        .env("ASTRA_KNOWLEDGE_DIR", knowledge.path())
        .args(["project", "run", "demo", "check", "--json"])
        .assert()
        .success();

    let output = astra_with_path(home.path(), current.path())
        .env("ASTRA_KNOWLEDGE_DIR", knowledge.path())
        .args(["knowledge", "verifications", "demo", "--json"])
        .output()
        .expect("knowledge output");
    assert!(output.status.success());
    let json: Value = serde_json::from_slice(&output.stdout).expect("knowledge JSON");
    let claims = json["claims"].as_array().expect("claims");
    assert_eq!(claims.len(), 1);
    assert_eq!(claims[0]["category"], "verification");
    assert_eq!(claims[0]["value"]["verdict"], "verified_check");
    assert!(claims[0]["evidence"][0]["fingerprints"].is_array());
    assert!(!output
        .stdout
        .windows(b"terminal output".len())
        .any(|window| window == b"terminal output"));

    fs::write(project.path().join("src/lib.rs"), "pub fn changed() {}\n").expect("changed source");
    let stale = astra_with_path(home.path(), current.path())
        .env("ASTRA_KNOWLEDGE_DIR", knowledge.path())
        .args(["knowledge", "verifications", "demo", "--json"])
        .output()
        .expect("stale knowledge output");
    assert!(stale.status.success());
    let stale_json: Value = serde_json::from_slice(&stale.stdout).expect("stale JSON");
    assert_eq!(stale_json["claims"][0]["validity"], "stale");
}

#[test]
fn project_run_real_check_propagates_child_failure() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = git_project();
    write_config(home.path(), &[("demo", project.path())]);
    fs::write(project.path().join("src/lib.rs"), "pub fn broken( {}\n").expect("invalid source");

    astra_with_path(home.path(), current.path())
        .args(["project", "run", "demo", "check"])
        .assert()
        .failure()
        .stderr(predicate::str::contains(
            "cargo check failed with exit code",
        ));
}

#[test]
fn project_run_real_check_rejects_non_git_projects() {
    let home = tempdir().expect("home");
    let current = tempdir().expect("current directory");
    let project = project();
    write_config(home.path(), &[("demo", project.path())]);

    astra_with_path(home.path(), current.path())
        .args(["project", "run", "demo", "check"])
        .assert()
        .failure()
        .stderr("astra: real execution currently requires a Git repository\n");
}
